import{A as E,a as g,S as j,i as x}from"./assets/vendor-_vbJqNT9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function n(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(o){if(o.ep)return;o.ep=!0;const s=n(o);fetch(o.href,s)}})();(()=>{const e={openModalBtn:document.querySelector("[data-menu-open]"),closeModalBth:document.querySelector("[data-menu-close]"),modalBtns:document.querySelectorAll(".modal-nav-link"),modal:document.querySelector("[data-modal]"),body:document.body};e.openModalBtn.addEventListener("click",t),e.closeModalBth.addEventListener("click",t),e.modalBtns.forEach(n=>{n.addEventListener("click",t)});function t(){e.modal.classList.toggle("is-open"),e.modal.classList.contains("is-open")?e.body.style.overflow="hidden":e.body.style.overflow=""}})();document.addEventListener("DOMContentLoaded",()=>{const e=[document.getElementById("theme-toggle"),document.getElementById("theme-toggle1")],t=document.querySelectorAll("[data-theme]"),n=localStorage.getItem("theme")||"light";t.forEach(r=>{r.setAttribute("data-theme",n)}),e.forEach(r=>{r.checked=n==="dark"}),e.forEach(r=>{r.addEventListener("change",()=>{const o=r.checked?"dark":"light";t.forEach(s=>{s.setAttribute("data-theme",o)}),e.forEach(s=>{s.checked=r.checked}),localStorage.setItem("theme",o)})})});const B="/command-project-portfolio/assets/10project2x-BvMudFNk.png",M="/command-project-portfolio/assets/11project2x-lUoKRskF.png",S="/command-project-portfolio/assets/12project2x-BDH3GoOm.png",I="/command-project-portfolio/assets/9project2x-CjkCjDSS.png",q="/command-project-portfolio/assets/8project2x-Beekt7gy.png",P="/command-project-portfolio/assets/7project2x-BnjIUlir.png",T="/command-project-portfolio/assets/6project2x-Co-_3AM6.png",O="/command-project-portfolio/assets/5project2x-BqgwRwZ7.png",C="/command-project-portfolio/assets/2project2x-CpyD6xhI.png",A="/command-project-portfolio/assets/1project2x-C868exiM.png",N=document.querySelector(".LoadImg"),h=document.querySelector(".projectBtnLoad"),D=[{src:B,name:"power pulse webservice"},{src:M,name:"wallet webservice"},{src:S,name:"English excellence webservice"},{src:I,name:"green harvest online store"},{src:q,name:"vyshyvanka vibes Landing Page"},{src:P,name:"mimino website"},{src:T,name:"chego jewelry website"},{src:O,name:"fruitbox online store"},{src:C,name:"energy flow webservice"},{src:A,name:"starlight studio landing page"}];let c=0;const R=e=>`
  <div class="wrapLoadImg">
  <ul class="wrapCarcass">
  <li><img class="imgWrap" src="${e.src}" heigth="500" width="1000" alt=""></li>
  <li><a class="siteLoad" href="https://www.edu.goit.global/uk/homepage" target="_blank" rel="nofollow"><p class="loadText">${e.name}</p></a></li>
  </ul>
</div>`,$=e=>{let t=10,n=2;c<t&&(N.innerHTML+=D.slice(c,c+n).map(r=>R(r)).join(""),c+=n,c>=t&&(h.style.display="none"))};h.addEventListener("click",$);document.addEventListener("DOMContentLoaded",()=>{new E("#questions-list",{duration:250,showMultiple:!1}).open(0)});document.addEventListener("DOMContentLoaded",()=>{const e=document.getElementById("contact-form"),t=document.getElementById("modal"),n=document.getElementById("modal-message"),r=document.querySelector(".close"),o=document.body,s=()=>{t.classList.remove("is-open"),o.style.overflow=""};r.addEventListener("click",s),window.addEventListener("click",a=>{a.target===t&&s()}),window.addEventListener("keydown",a=>{a.key==="Escape"&&s()}),e.addEventListener("submit",async a=>{a.preventDefault();const b=e.email.value.trim(),L=e.message.value.trim();try{(await fetch("https://portfolio-js.b.goit.study/api-docs/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:b,message:L})})).ok?(n.innerHTML=`
          <h3 class="modal-success">Thank you for your interest in cooperation!</h3>
          <p class="modal-info">The manager will contact you shortly to discuss further details and opportunities for cooperation. Please stay in touch.</p>`,e.reset()):n.textContent="There was an error with your request. Please try again.",t.classList.add("is-open"),o.style.overflow="hidden"}catch{n.textContent="An error occurred. Please try again.",t.classList.add("is-open"),o.style.overflow="hidden"}})});g.defaults.baseURL="https://portfolio-js.b.goit.study/api/";const l=document.querySelector(".btn-next"),m=document.querySelector(".btn-prev"),u=document.querySelector(".error-message"),F=document.querySelector(".reviews-navigation"),p=document.querySelector(".carousel-wrapper");let f;window.addEventListener("resize",d);document.addEventListener("keydown",e=>{e.key==="ArrowRight"?y():e.key==="ArrowLeft"&&v()});p.addEventListener("touchmove",w);p.addEventListener("mousemove",w);function y(){i.slideNext(),d()}function v(){i.slidePrev(),d()}function d(){i.isBeginning?m.classList.add("button-disabled"):m.classList.remove("button-disabled"),i.isEnd?l.classList.add("button-disabled"):l.classList.remove("button-disabled")}l.addEventListener("click",y);m.addEventListener("click",v);const i=new j(".swiper",{slidesPerView:1,spaceBetween:16,speed:800,breakpoints:{0:{slidesPerView:1},768:{slidesPerView:1},1280:{slidesPerView:2}}});async function H(){try{return(await g("/reviews")).data}catch{u.classList.remove("hidden"),F.classList.add("hidden"),z();return}}async function V(){const e=await H();if(e.length===0){u.classList.remove("hidden");return}p.insertAdjacentHTML("beforeend",U(e)),i.update(),d()}V();function U(e){return e.map(({review:t,author:n,avatar_url:r})=>`
      <div class="swiper-slide feedback-item">
        <p class="feedback-text">${t}</p>
        <div class="feedback-info">
          <img src="${r}" alt="${n}" class="feedback-avatar" />
          <span class="feedback-author">${n}</span>
        </div>
      </div>
    `).join("")}function z(){const e=new IntersectionObserver(K,{threshold:1});return e.observe(u),e}function K(e){e.forEach(t=>{t.isIntersecting&&x.error({message:"Reviews not found! Please try again later.",position:"topRight"})})}function w(){clearTimeout(f),f=setTimeout(d,200)}
//# sourceMappingURL=index.js.map
